name: carnd-advdl-odlab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
    - defaults
    - conda-forge/label/broken
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scipy
    - ffmpeg
    - imageio==2.1.2
    - pip:
        - moviepy
        - tensorflow==1.4
